apiVersion: v1
kind: Namespace
metadata:
  name: todo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: todo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - image: index.docker.io/mk51/todo:latest
        imagePullPolicy: Always
        name: todo
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: todo
  namespace: todo
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: todo
